Nop.Plugin.Misc.CustomTheme/Controllers/CustomThemeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Nop.Services.Configuration;
using Nop.Services.Messages;
using Nop.Web.Framework;
using Nop.Web.Framework.Controllers;

namespace Nop.Plugin.Misc.CustomTheme.Controllers;

[Area(AreaNames.ADMIN)]
public class CustomThemeController : BasePluginController
{
    private readonly ISettingService _settingService;
    private readonly INotificationService _notificationService;
    public CustomThemeController(ISettingService settingService, INotificationService notificationService)
    {
        _settingService = settingService;
        _notificationService = notificationService;
    }

    public IActionResult Configure()
    {
        var model = _settingService.LoadSetting<CustomThemeSettings>() ?? new CustomThemeSettings();
        return View("Plugins/Misc.CustomTheme/Views/Configure.cshtml", model);
    }

    [HttpPost]
    public IActionResult Configure(CustomThemeSettings settings)    
    {
        _settingService.SaveSetting(settings);

        _notificationService.SuccessNotification("Custom settings configuration added successfully");

        return Configure();
    }
}

Nop.Plugin.Misc.CustomTheme/Views/Configure.cshtml
@model CustomThemeSettings

@{
    Layout = "_ConfigurePlugin";
    NopHtml.SetActiveMenuItemSystemName("Custom Theme Plugin");
}

<div class="container">
    <form method="post" asp-controller="CustomTheme" asp-action="Configure">
        <div class="row">
            <div class="col-sm-6">
                <div class="form-group row">
                    <label class="col-sm-3 col-form-label">Name:</label>
                    <div class="col-sm-9">
                        <input asp-for="Name" type="text" class="form-control" id="name">
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-3 col-form-label">Message:</label>
                    <div class="col-sm-9">
                        <input asp-for="Message" type="text" class="form-control" id="message">
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-3 col-form-label">Date:</label>
                    <div class="col-sm-9">
                        <input asp-for="Date" type="date" class="form-control" id="date">
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-sm-9 offset-sm-3 mt-1 text-right">
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>

<script type="text/javascript">
    $(document).ready(function () {
        $('#date').val(toDateInputValue(new Date()));
    });

    function toDateInputValue(date) {
        var local = new Date(date);
        local.setMinutes(date.getMinutes() - date.getTimezoneOffset());
        return local.toJSON().slice(0, 10);
    }
</script>